### ISSUE TITLE
response stream error is not catched by context

### ISSUE THREAD

**Issue by orangemi** [toajs/toa#3]
Here is a very simple code to generate an unlimited stream to client and log almost every event that emit by toajs:
```js
'use strict'
const stream = require('stream')
const toa = require('toa')
const upstream = toa({onerror: function (error) {
  console.log('this.onerror', error)
}})
upstream.onerror = function (err) {
  console.log('application error', err)
}
upstream.use(function * () {
  console.log('request start')
  this.on('end', () => console.log('context end'))
  this.res.on('close', () => console.log('this.res close'))
  this.res.on('aborted', () => console.log('this.res aborted'))
  this.res.on('finish', () => console.log('this.res finish'))
  this.res.on('error', (err) => console.log('this.res error', err))
  this.req.on('error', (err) => console.log('this.req error', err))
})

upstream.use(function * () {
  let s = stream.PassThrough()
  setInterval(function () {
    s.write(new Buffer(4096))
  }, 100)
  s.on('error', (err) => console.log('stream error', err))
  this.body = s
})
upstream.listen(3001, function () {
  console.log('upstream listen to 3001')
})
```

In another terminal I run curl and press Ctrl+C to send the interrupt signal the request. I found only application catched the error and this is not expected:
```
upstream listen to 3001
request start
context end
application error { Error: read ECONNRESET
    at exports._errnoException (util.js:1007:11)
    at TCP.onread (net.js:563:26)
  code: 'ECONNRESET',
  errno: 'ECONNRESET',
  syscall: 'read',
  headerSent: true }
this.res close
```

Deeply debug here is the error source:  https://github.com/toajs/toa/blob/master/lib/context.js#L157
Since I send the interrupt singal in the terminal, the socket built in lib/net.js is already been destroyed. The error was just about the stream. It make sence the error should be only export to the application not the request context because context closed before.

However the error should be **IGNORED naturally** I think.

**Comment by zensh** [comment]
@orangemi The library should not ignore any error. You can use [error.context](https://github.com/toajs/toa/commit/b51ee7fb0b65aa3985e59ec9859ffc6dc975c593#diff-5372f626ee15242f1e2c6eb31655b4faR280) to check what happened.
